apiVersion: v1
kind: Namespace
metadata:
  name: ember-csi-lvm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loop-back-pvc
  namespace: ember-csi-lvm
  labels:
    app: loop-back-lvm
spec:
  storageClassName: local
  accessModes:
     - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loopback-deployment
  namespace: ember-csi-lvm
  labels:
    app: loop-back-lvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loop-back-lvm
  template:
    metadata:
      labels:
        app: loop-back-lvm
    spec:
      containers:
      - name: loop-back-lvm
        image: registry:5000/loop-back-lvm:latest
        env:
        - name: DEVICE_SIZE
          value: 25G
        - name: DATA_DIR
          value: /data
        volumeMounts:
        - name: local-storage
          mountPath: /data
        securityContext:
          privileged: true
        readinessProbe:
          exec:
            command:
            - cat
            - /ready
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: loop-back-pvc
        